apiVersion: apps/v1
kind: Deployment
metadata:
  name: submission-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: submission-service
  template:
    metadata:
      labels:
        app: submission-service
    spec:
      containers:
        - name: submission-service
          image: yashveersingh83/submissionservice
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmessagequeue"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: REDIS_HOST
              value: "redis-cache"
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: submission-service
spec:
  selector:
    app: submission-service
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8080
