services:
  redisCache:
    image: redis:latest 
    container_name: redisCache
    ports:
      - "6379:6379"
    networks:
      - my-network
    volumes:
      - redis-data:/data

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redisCache:6379
    depends_on:
      - redisCache
    networks:
      - my-network

  rabbitMessageQueue:
    image: rabbitmq:management
    container_name: rabbitMessageQueue
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    networks:
      - my-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "7080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    networks:
      - my-network
    volumes:
      - keycloak-data:/opt/keycloak/data

  submission-service:
    image: submission-service
    container_name: submissionservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8080"
    depends_on:
      - redisCache
      - rabbitMessageQueue
      - keycloak
    environment:
      - RABBITMQ_HOST=rabbitMessageQueue
      - KEYCLOAK_AUTH_URL=http://keycloak:7080/realms/Datawrangler/protocol/openid-connect/auth
      - KEYCLOAK_METADATA_ADDRESS=http://keycloak:7080/realms/Datawrangler/.well-known/openid-configuration
      - KEYCLOAK_ISSUER=http://keycloak:7080/realms/Datawrangler
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - my-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  redis-data:
  rabbitmq-data:
  keycloak-data:
  grafana-storage:
