global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'submission-service'
    static_configs:
      - targets: ['submissionservice:8080']
  - job_name: 'redis'
    static_configs:
      - targets: ['redisCache:6379']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitMessageQueue:5672']
  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak:8080']