global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'submission-service'
    static_configs:
      - targets: ['submissionservice:8080']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitMessageQueue:15692']


      
